добавляет разметку главной страницы
htmlacademy-adaptive/1966385-cat-energy-28 pull request #3
Opened 2023-04-06 18:57 UTC by kol5ack

2023-04-09 14:11 UTC, kenakula requested changes
хороший темп, продолжай)

2023-04-09 14:11 UTC, kenakula commented on catalog.html
> +  </dl>
отличный выбор)

2023-04-13 09:33 UTC, kenakula approved these changes

2023-04-16 12:15 UTC, merged

2023-04-16 12:35 UTC, kol5ack commented on catalog.html
> +  </dl>
Поправил